// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_neighbourhoods
List compute_neighbourhoods(NumericVector sx, NumericVector sy, NumericVector ex, NumericVector ey, double eps, double w_perp, double w_par, double w_angle);
RcppExport SEXP _TRACLUS_compute_neighbourhoods(SEXP sxSEXP, SEXP sySEXP, SEXP exSEXP, SEXP eySEXP, SEXP epsSEXP, SEXP w_perpSEXP, SEXP w_parSEXP, SEXP w_angleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sy(sySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type w_perp(w_perpSEXP);
    Rcpp::traits::input_parameter< double >::type w_par(w_parSEXP);
    Rcpp::traits::input_parameter< double >::type w_angle(w_angleSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_neighbourhoods(sx, sy, ex, ey, eps, w_perp, w_par, w_angle));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TRACLUS_compute_neighbourhoods", (DL_FUNC) &_TRACLUS_compute_neighbourhoods, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_TRACLUS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
