# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_neighbourhoods <- function(sx, sy, ex, ey, eps, w_perp = 1.0, w_par = 1.0, w_angle = 1.0) {
    .Call(`_TRACLUS_compute_neighbourhoods`, sx, sy, ex, ey, eps, w_perp, w_par, w_angle)
}

